+ source ../comm_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ tar -xf tmp_test.tar
tar: tmp_test.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
++ pushd ../
~/mugen/testcases/embedded-test/third_party_packages_test ~/mugen/testcases/embedded-test/third_party_packages_test/oe_test_popt_test_001
++ [[ -z '' ]]
+++ pwd
++ CUR=/root/mugen/testcases/embedded-test/third_party_packages_test
++ tar -xf dejagnu.tar
tar: dejagnu.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
++ RUNTEST=/root/mugen/testcases/embedded-test/third_party_packages_test/dejagnu/bin/runtest
++ chmod +x /root/mugen/testcases/embedded-test/third_party_packages_test/dejagnu/bin/runtest
chmod: cannot access '/root/mugen/testcases/embedded-test/third_party_packages_test/dejagnu/bin/runtest': No such file or directory
++ export RUNTEST
++ popd
~/mugen/testcases/embedded-test/third_party_packages_test/oe_test_popt_test_001
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Apr 29 03:32:45 2023 - INFO  - Start to run test.
+ pushd ./tmp_test/tests
oe_test_popt_test_001.sh: line 25: pushd: ./tmp_test/tests: No such file or directory
+ chmod 777 ./Makefile ./oe_test_popt_test_001.sh
+ sh ./testit.sh
+ cat tmp_log.log
sh: ./testit.sh: No such file or directory
+ awk 'END {print}' tmp_log.log
+ grep Passed.
+ CHECK_RESULT 1 0 0 'run popt testcase fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='run popt testcase fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'run popt testcase fail'
+ LOG_ERROR 'run popt testcase fail'
+ message='run popt testcase fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'run popt testcase fail'
Sat Apr 29 03:32:46 2023 - ERROR - run popt testcase fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_popt_test_001.sh line 33'
+ message='oe_test_popt_test_001.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_popt_test_001.sh line 33'
Sat Apr 29 03:32:47 2023 - ERROR - oe_test_popt_test_001.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ popd
oe_test_popt_test_001.sh: line 35: popd: directory stack empty
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Apr 29 03:32:47 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Apr 29 03:32:48 2023 - ERROR - failed to execute the case.
+ exit 1
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_popt_test_001.sh post_test'
+ message='oe_test_popt_test_001.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_popt_test_001.sh post_test'
Sat Apr 29 03:32:49 2023 - INFO  - oe_test_popt_test_001.sh post_test
