+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120230428205511 /tmp/point220230428205511 /tmp/point320230428205511
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Fri Apr 28 21:25:47 2023 - INFO  - Start environment preparation.
++ date +%Y%m%d%H%M%S
+ cur_date=20230428212547
+ point_list=($(CREATE_FS "ext3 ext4 xfs"))
++ CREATE_FS 'ext3 ext4 xfs'
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230428212547
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230428212547
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vdt
+++ disk_name=/dev/vdt
+++ pvcreate /dev/vdt -f
+++ [[ 5 -eq 0 ]]
++++ pvcreate /dev/vdt
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=test_vggroup20230428204559
+++ printf test_vggroup20230428204559
++ vggroup=test_vggroup20230428204559
++ count=1
++ msg='test_vggroup20230428204559 '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230428212547
++ point=/tmp/point120230428212547
++ lvcreate -n test_lv120230428212547 -L 512M test_vggroup20230428204559 -y
  Volume group "test_vggroup20230428204559" has insufficient free space (124 extents): 128 required.
++ mkfs -t ext3 /dev/test_vggroup20230428204559/test_lv120230428212547
mke2fs 1.46.5 (30-Dec-2021)
The file /dev/test_vggroup20230428204559/test_lv120230428212547 does not exist and no size was specified.
++ mkdir /tmp/point120230428212547
++ mount /dev/test_vggroup20230428204559/test_lv120230428212547 /tmp/point120230428212547
mount: /tmp/point120230428212547: special device /dev/test_vggroup20230428204559/test_lv120230428212547 does not exist.
++ msg='test_vggroup20230428204559 /tmp/point120230428212547 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230428212547
++ point=/tmp/point220230428212547
++ lvcreate -n test_lv220230428212547 -L 512M test_vggroup20230428204559 -y
  Volume group "test_vggroup20230428204559" has insufficient free space (124 extents): 128 required.
++ mkfs -t ext4 /dev/test_vggroup20230428204559/test_lv220230428212547
mke2fs 1.46.5 (30-Dec-2021)
The file /dev/test_vggroup20230428204559/test_lv220230428212547 does not exist and no size was specified.
++ mkdir /tmp/point220230428212547
++ mount /dev/test_vggroup20230428204559/test_lv220230428212547 /tmp/point220230428212547
mount: /tmp/point220230428212547: special device /dev/test_vggroup20230428204559/test_lv220230428212547 does not exist.
++ msg='test_vggroup20230428204559 /tmp/point120230428212547 /tmp/point220230428212547 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230428212547
++ point=/tmp/point320230428212547
++ lvcreate -n test_lv320230428212547 -L 512M test_vggroup20230428204559 -y
  Volume group "test_vggroup20230428204559" has insufficient free space (124 extents): 128 required.
++ mkfs -t xfs /dev/test_vggroup20230428204559/test_lv320230428212547
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point320230428212547
++ mount /dev/test_vggroup20230428204559/test_lv320230428212547 /tmp/point320230428212547
mount: /tmp/point320230428212547: special device /dev/test_vggroup20230428204559/test_lv320230428212547 does not exist.
++ msg='test_vggroup20230428204559 /tmp/point120230428212547 /tmp/point220230428212547 /tmp/point320230428212547 '
++ count=4
++ echo test_vggroup20230428204559 /tmp/point120230428212547 /tmp/point220230428212547 /tmp/point320230428212547
+ ext3_point=/tmp/point120230428212547
+ ext4_point=/tmp/point220230428212547
+ xfs_point=/tmp/point320230428212547
+ echo 'test ext3'
+ echo 'test ext4'
+ echo 'test xfs'
+ mkdir /tmp/point120230428212547/testDir
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Apr 28 21:25:52 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 21:25:53 2023 - INFO  - Start to run test.
+ ln /tmp/point120230428212547/testDir /tmp/hard_link20230428212547
+ grep 'hard link not allowed for directory'
ln: /tmp/point120230428212547/testDir: hard link not allowed for directory
+ CHECK_RESULT 0 0 0 'Create hard link for directory unexpectly.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Create hard link for directory unexpectly.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ln /tmp/point120230428212547/testnonexist /tmp/hard_link20230428212547
+ grep 'No such file or directory'
ln: failed to access '/tmp/point120230428212547/testnonexist': No such file or directory
+ CHECK_RESULT 0 0 0 'Create hard link for non-exist directory unexpectly.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Create hard link for non-exist directory unexpectly.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ln /tmp/point120230428212547/testFile1 /tmp/point220230428212547/hardFile
+ grep 'Invalid cross-device link'
+ CHECK_RESULT 1 0 0 'Create hard link between ext3 and ext4 unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Create hard link between ext3 and ext4 unexpectly.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Create hard link between ext3 and ext4 unexpectly.'
+ LOG_ERROR 'Create hard link between ext3 and ext4 unexpectly.'
+ message='Create hard link between ext3 and ext4 unexpectly.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Create hard link between ext3 and ext4 unexpectly.'
Fri Apr 28 21:25:54 2023 - ERROR - Create hard link between ext3 and ext4 unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_hardlink_fail.sh line 42'
+ message='oe_test_FSIO_create_hardlink_fail.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_hardlink_fail.sh line 42'
Fri Apr 28 21:25:54 2023 - ERROR - oe_test_FSIO_create_hardlink_fail.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ ln /tmp/point220230428212547/testFile1 /tmp/point320230428212547/hardFile
+ grep 'Invalid cross-device link'
+ CHECK_RESULT 1 0 0 'Create hard link between ext4 and xfs unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Create hard link between ext4 and xfs unexpectly.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Create hard link between ext4 and xfs unexpectly.'
+ LOG_ERROR 'Create hard link between ext4 and xfs unexpectly.'
+ message='Create hard link between ext4 and xfs unexpectly.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Create hard link between ext4 and xfs unexpectly.'
Fri Apr 28 21:25:55 2023 - ERROR - Create hard link between ext4 and xfs unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_hardlink_fail.sh line 44'
+ message='oe_test_FSIO_create_hardlink_fail.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_hardlink_fail.sh line 44'
Fri Apr 28 21:25:56 2023 - ERROR - oe_test_FSIO_create_hardlink_fail.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ ln /tmp/point320230428212547/testFile1 /tmp/point120230428212547/hardFile
+ grep 'Invalid cross-device link'
+ CHECK_RESULT 1 0 0 'Create hard link between xfs and ext3 unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Create hard link between xfs and ext3 unexpectly.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Create hard link between xfs and ext3 unexpectly.'
+ LOG_ERROR 'Create hard link between xfs and ext3 unexpectly.'
+ message='Create hard link between xfs and ext3 unexpectly.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Create hard link between xfs and ext3 unexpectly.'
Fri Apr 28 21:25:57 2023 - ERROR - Create hard link between xfs and ext3 unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_create_hardlink_fail.sh line 46'
+ message='oe_test_FSIO_create_hardlink_fail.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_create_hardlink_fail.sh line 46'
Fri Apr 28 21:25:58 2023 - ERROR - oe_test_FSIO_create_hardlink_fail.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Apr 28 21:25:59 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Apr 28 21:25:59 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Apr 28 21:26:00 2023 - INFO  - Start to restore the test environment.
++ echo test_vggroup20230428204559 /tmp/point120230428212547 /tmp/point220230428212547 /tmp/point320230428212547
+ list='test_vggroup20230428204559 /tmp/point120230428212547 /tmp/point220230428212547 /tmp/point320230428212547'
+ REMOVE_FS 'test_vggroup20230428204559 /tmp/point120230428212547 /tmp/point220230428212547 /tmp/point320230428212547'
+ point_list=($1)
++ seq 0 3
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=test_vggroup20230428204559
++ df -T
++ grep test_vggroup20230428204559
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230428212547
++ df -T
++ grep /tmp/point120230428212547
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230428212547
++ df -T
++ grep /tmp/point220230428212547
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230428212547
++ df -T
++ grep /tmp/point320230428212547
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Apr 28 21:26:02 2023 - INFO  - End to restore the test environment.
