+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Sat Apr 29 02:44:26 2023 - INFO  - Start executing testcase.
+ find /dev/mem -type f -user root -group root -perm 640
+ CHECK_RESULT 0 0 0 'check /dev/mem file right fail'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check /dev/mem file right fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ find /etc/fstab -type f -user root -group root -perm 600
+ CHECK_RESULT 0 0 0 'check /etc/fstab file right fail'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check /etc/fstab file right fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ find /etc/group -type f -user root -group root -perm 644
/etc/group
+ CHECK_RESULT 0 0 0 'check /etc/group file right fail'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check /etc/group file right fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ find /etc/init.d/ -type f -user root -group root -perm 750
+ CHECK_RESULT 0 0 0 'check /etc/init.d/ file right fail'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check /etc/init.d/ file right fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ 'find /etc/init.d/* -type f -user root -group root -perm 750 | wc -l'
oe_test_check_file_sys_protect_002.sh: line 38: find /etc/init.d/* -type f -user root -group root -perm 750 | wc -l: No such file or directory
+ getFileNum=
++ 'find /etc/init.d/* -type f | wc -l'
oe_test_check_file_sys_protect_002.sh: line 39: find /etc/init.d/* -type f | wc -l: No such file or directory
+ allFileNum=
+ test '' -eq ''
oe_test_check_file_sys_protect_002.sh: line 40: test: : integer expression expected
+ CHECK_RESULT 2 0 1 'check /etc/init.d/* file right fail'
+ actual_result=2
+ expect_result=0
+ mode=1
+ error_log='check /etc/init.d/* file right fail'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 1 -eq 0 ']'
+ test 2x == 0x
+ return 0
+ find /etc/passwd -type f -user root -group root -perm 644
/etc/passwd
+ CHECK_RESULT 0 0 0 'check /etc/passwd file right fail'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check /etc/passwd file right fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ find /etc/securetty -type f -user root -group root -perm 600
find: ‘/etc/securetty’: No such file or directory
+ CHECK_RESULT 1 0 0 'check /etc/securetty file right fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check /etc/securetty file right fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check /etc/securetty file right fail'
+ LOG_ERROR 'check /etc/securetty file right fail'
+ message='check /etc/securetty file right fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check /etc/securetty file right fail'
Sat Apr 29 02:44:27 2023 - ERROR - check /etc/securetty file right fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_check_file_sys_protect_002.sh line 47'
+ message='oe_test_check_file_sys_protect_002.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_check_file_sys_protect_002.sh line 47'
Sat Apr 29 02:44:28 2023 - ERROR - oe_test_check_file_sys_protect_002.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ find /etc/security/opasswd -type f -user root -group root -perm 600
/etc/security/opasswd
+ CHECK_RESULT 0 0 0 'check /etc/security/opasswd file right fail'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check /etc/security/opasswd file right fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ find /etc/shadow -type f -user root -group root -perm 600
+ CHECK_RESULT 0 0 0 'check /etc/shadow file right fail'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check /etc/shadow file right fail'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ 'find /etc/ssh/*key -type f -user root -group root -perm 400 | wc -l'
oe_test_check_file_sys_protect_002.sh: line 55: find /etc/ssh/*key -type f -user root -group root -perm 400 | wc -l: No such file or directory
+ getFileNum=
++ 'find /etc/ssh/*key -type f | wc -l'
oe_test_check_file_sys_protect_002.sh: line 56: find /etc/ssh/*key -type f | wc -l: No such file or directory
+ allFileNum=
+ test '' -eq ''
oe_test_check_file_sys_protect_002.sh: line 57: test: : integer expression expected
+ CHECK_RESULT 2 0 1 'check /etc/ssh/*key file right fail'
+ actual_result=2
+ expect_result=0
+ mode=1
+ error_log='check /etc/ssh/*key file right fail'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 1 -eq 0 ']'
+ test 2x == 0x
+ return 0
++ 'find find /etc/ssh/*key.pub -type f -user root -group root -perm 644 | wc -l'
oe_test_check_file_sys_protect_002.sh: line 60: find find /etc/ssh/*key.pub -type f -user root -group root -perm 644 | wc -l: No such file or directory
+ getFileNum=
++ 'find /etc/ssh/*key.pub -type f | wc -l'
oe_test_check_file_sys_protect_002.sh: line 61: find /etc/ssh/*key.pub -type f | wc -l: No such file or directory
+ allFileNum=
+ test '' -eq ''
oe_test_check_file_sys_protect_002.sh: line 62: test: : integer expression expected
+ CHECK_RESULT 2 0 1 'check /etc/ssh/*key.pub file right fail'
+ actual_result=2
+ expect_result=0
+ mode=1
+ error_log='check /etc/ssh/*key.pub file right fail'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 1 -eq 0 ']'
+ test 2x == 0x
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Sat Apr 29 02:44:29 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Apr 29 02:44:30 2023 - ERROR - failed to execute the case.
+ exit 1
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_check_file_sys_protect_002.sh post_test'
+ message='oe_test_check_file_sys_protect_002.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_check_file_sys_protect_002.sh post_test'
Sat Apr 29 02:44:30 2023 - INFO  - oe_test_check_file_sys_protect_002.sh post_test
