+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Apr 28 21:38:13 2023 - INFO  - Start to prepare the database config.
+ DNF_INSTALL gcc
+ pkgs=gcc
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs gcc --node 1 --tempfile ''
Fri Apr 28 21:38:24 2023 - INFO  - pkgs:(gcc) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ [[ ! -f ./aio_read_file ]]
+ make
In file included from /usr/include/sys/socket.h:33,
                 from aio_read_file.c:3:
/usr/include/bits/socket.h:359:11: fatal error: asm/socket.h: No such file or directory
  359 | # include <asm/socket.h>
      |           ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: default] Error 1
+ echo 'append read only file'
++ ls -l test_aio_read_file
++ awk '{print $5}'
+ filebytes=22
+ LOG_INFO 'End to prepare the database config.'
+ message='End to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the database config.'
Fri Apr 28 21:38:26 2023 - INFO  - End to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Apr 28 21:38:26 2023 - INFO  - Start to run test.
++ echo test_aio_read_file
++ ./aio_read_file
oe_test_FSIO_aio_read.sh: line 34: ./aio_read_file: No such file or directory
+ readbytes=
+ CHECK_RESULT 22 0 'Aio read file failed.'
+ actual_result=22
+ expect_result=0
+ mode='Aio read file failed.'
+ error_log=
+ exit_mode=0
+ '[' -z 22 ']'
+ '[' Aio read file failed. -eq 0 ']'
/root/mugen/libs/locallibs/common_lib.sh: line 38: [: too many arguments
+ test 22x == 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Apr 28 21:38:27 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Fri Apr 28 21:38:28 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Apr 28 21:38:29 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Apr 28 21:38:30 2023 - WARN  - no thing to do.
+ return 0
+ rm -f test_aio_read_file
+ make clean
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Apr 28 21:38:31 2023 - INFO  - End to restore the test environment.
